variables:
  GIT_DEPTH: 0

mirror_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git remote add mirror git@github.com:Alb06/RecruitmentSite.git || true
    - git branch main || true
    - git push --mirror mirror
  # only:
  #   - main


sync_issues_to_github:
  stage: deploy
  image: python:3.11
  before_script:
    - pip install requests
  script:
    - python scripts/sync_issues.py
  only:
    - main


# push_current_to_github_main:
#   stage: deploy
#   image: alpine:latest
#   before_script:
#     - apk add --no-cache git openssh
#   script:
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
#     - chmod 600 ~/.ssh/id_ed25519
#     - ssh-keyscan github.com >> ~/.ssh/known_hosts
#     - git remote add mirror git@github.com:Alb06/RecruitmentSite.git || true
#     - git branch main || true
#     - git push --mirror mirror HEAD:main -f
#   except:
#     - main 
