version: '3.8'

services:
  recrut.api:
    # Other configurations...
    volumes:
      - dataprotection-keys:/app/keys

  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: zahagadmin
      POSTGRES_PASSWORD: 24rnUZ42
      POSTGRES_DB: recrutdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/docker/volumes/pgdata/_data

volumes:
  pgdata:
  dataprotection-keys:
